// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFcPWjPIbKfNEjCINL6eaypsG4MaPKCL8',
    appId: '1:585591375705:android:ddca5da0f764049fbeee48',
    messagingSenderId: '585591375705',
    projectId: 'eurofarmaproject',
    storageBucket: 'eurofarmaproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFcPWjPIbKfNEjCINL6eaypsG4MaPKCL8',
    appId: '1:585591375705:ios:ddca5da0f764049fbeee48',
    messagingSenderId: '585591375705',
    projectId: 'eurofarmaproject',
    storageBucket: 'eurofarmaproject.firebasestorage.app',
    iosBundleId: 'com.eurofarma.sprint3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFcPWjPIbKfNEjCINL6eaypsG4MaPKCL8',
    appId: '1:585591375705:web:ddca5da0f764049fbeee48',
    messagingSenderId: '585591375705',
    projectId: 'eurofarmaproject',
    storageBucket: 'eurofarmaproject.firebasestorage.app',
  );
}
